name: askless
description: Flutter client of Askless framework, which facilitates building realtime servers for JavaScript and Flutter Apps

version: 1.0.1 # TODO onupdate:

environment:
  sdk: ">=2.1.0 <3.0.0"

homepage: https://github.com/WiseTap/askless-flutter-client/tree/dev/

repository: https://github.com/WiseTap/askless-flutter-client/tree/dev/

documentation: https://github.com/WiseTap/askless-flutter-client/blob/dev/documentation/english_documentation.md

issue_tracker: https://github.com/WiseTap/askless-flutter-client/issues

dependencies:
  flutter:
    sdk: flutter
  random_string: ^2.1.0
  synchronized: ^3.0.0
  connectivity: ^3.0.2
  web_socket_channel: ^2.0.0

dev_dependencies:
  test: ^1.17.8

#dev_dependencies:
#  flutter_test:
#    sdk: flutter

#flutter:
#  uses-material-design: true
